<?php

return [
    [
        "dish_id"=>"1",
        "order_id"=>"1",
        "quantity"=>"1"
    ],
    [
        "dish_id"=>"2",
        "order_id"=>"1",
        "quantity"=>"1"
    ],
    [
        "dish_id"=>"3",
        "order_id"=>"3",
        "quantity"=>"1"
    ],
    [
        "dish_id"=>"4",
        "order_id"=>"1",
        "quantity"=>"1"
    ],
    [
        "dish_id"=>"5",
        "order_id"=>"5",
        "quantity"=>"1"
    ],
    [
        "dish_id"=>"6",
        "order_id"=>"6",
        "quantity"=>"1"
    ],
    [
        "dish_id"=>"7",
        "order_id"=>"7",
        "quantity"=>"1"
    ],
    [
        "dish_id"=>"8",
        "order_id"=>"8",
        "quantity"=>"1"
    ],
    [
        "dish_id"=>"9",
        "order_id"=>"9",
        "quantity"=>"1"
    ],
    [
        "dish_id"=>"10",
        "order_id"=>"10",
        "quantity"=>"1"
    ],
    [
        "dish_id"=>"11",
        "order_id"=>"11",
        "quantity"=>"1"
    ],
    [
        "dish_id"=>"12",
        "order_id"=>"12",
        "quantity"=>"1"
    ],
    [
        "dish_id"=>"13",
        "order_id"=>"13",
        "quantity"=>"1"
    ],
    [
        "dish_id"=>"14",
        "order_id"=>"14",
        "quantity"=>"1"
    ],
    [
        "dish_id"=>"15",
        "order_id"=>"15",
        "quantity"=>"1"
    ],
    [
        "dish_id"=>"16",
        "order_id"=>"16",
        "quantity"=>"1"
    ],
    [
        "dish_id"=>"17",
        "order_id"=>"17",
        "quantity"=>"1"
    ],
    [
        "dish_id"=>"18",
        "order_id"=>"18",
        "quantity"=>"1"
    ],
    [
        "dish_id"=>"19",
        "order_id"=>"19",
        "quantity"=>"1"
    ],
    [
        "dish_id"=>"20",
        "order_id"=>"20",
        "quantity"=>"1"
    ],
    [
        "dish_id"=>"21",
        "order_id"=>"21",
        "quantity"=>"1"
    ],
    [
        "dish_id"=>"22",
        "order_id"=>"22",
        "quantity"=>"1"
    ],
    
    
];

